name: "Get & Cache Dependencies"
description: "Get the depencies with NPM and cache them."
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Whether cache was used."
    value: ${{steps.install_id.outputs.cache_name}}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install_id
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache_name='${{inputs.caching}}'" >> $GITHUB_OUTPUT
